#!/usr/bin/env bash
#
# traefik-backup.sh — extract stateful Traefik config from the VM over SSH.
#
# Runs from the workstation. Pulls the data that can't be regenerated by
# terraform + traefik-setup.sh:
#
#   - letsencrypt/acme.json   LE wildcard cert + ACME account state
#                             (re-issuing hits Let's Encrypt rate limits)
#   - dynamic.d/              route definitions beyond 00-base.yml
#                             (traefik-setup.sh only owns 00-base.yml)
#   - .env                    dashboard htpasswd hash with its salt
#                             (re-runs of traefik-setup.sh produce a different hash)
#   - docker-compose.yml      kept for drift detection vs rebuilt version
#
# Produces in ${OUT_DIR}/:
#   traefik-backup-<host>-<timestamp>.tar.gz
#   traefik-backup-<host>-<timestamp>.sha256
#
# Idempotent — every invocation produces a fresh timestamped artefact, so
# re-running doesn't clobber prior backups.
#
# Uses SSH ControlMaster so the workstation is prompted for the key passphrase
# at most once per invocation.
#
# Override via env vars:
#   TRAEFIK_HOST   (default: 192.168.57.8)
#   TRAEFIK_USER   (default: sam)
#   TRAEFIK_DIR    (default: traefik)        path relative to user's home
#   OUT_DIR        (default: ./backups)      where to write tarball + manifest
#   SSH_KEY        (default: unset)          path to private key; agent used if unset
#
set -euo pipefail

TRAEFIK_HOST="${TRAEFIK_HOST:-192.168.57.8}"
TRAEFIK_USER="${TRAEFIK_USER:-sam}"
TRAEFIK_DIR="${TRAEFIK_DIR:-traefik}"
OUT_DIR="${OUT_DIR:-./backups}"
SSH_KEY="${SSH_KEY:-}"

# SSH ControlMaster: one TCP connection reused across all ssh/scp calls
# in this script — so we only prompt for the key passphrase once.
#
# %C is OpenSSH's hash of user+host+port; gives a short, deterministic socket
# name. Kept under /tmp because macOS's $TMPDIR can exceed the Unix-socket
# path limit (104 bytes) on its own.
SSH_CONTROL_PATH="/tmp/tb-ssh-%C"
SSH_OPTS=(
  -o "ControlMaster=auto"
  -o "ControlPath=${SSH_CONTROL_PATH}"
  -o "ControlPersist=60s"
  -o "StrictHostKeyChecking=accept-new"
  -o "ConnectTimeout=10"
)
if [[ -n "${SSH_KEY}" ]]; then
  SSH_OPTS+=(-i "${SSH_KEY}")
fi

# Paths to back up — relative to ~/${TRAEFIK_DIR}/ on the remote host.
# Missing paths are warned about and skipped, not treated as fatal.
TARGETS=(
  letsencrypt/acme.json
  dynamic.d
  .env
  docker-compose.yml
)

REMOTE_TARBALL=""

log() { printf '[traefik-backup] %s\n' "$*"; }
err() { printf '[traefik-backup] ERROR: %s\n' "$*" >&2; }

cleanup() {
  if [[ -n "${REMOTE_TARBALL}" ]]; then
    ssh "${SSH_OPTS[@]}" "${TRAEFIK_USER}@${TRAEFIK_HOST}" \
      "rm -f '${REMOTE_TARBALL}'" 2>/dev/null || true
  fi
  # Close the persistent SSH master; this also removes the control socket.
  ssh "${SSH_OPTS[@]}" -O exit "${TRAEFIK_USER}@${TRAEFIK_HOST}" 2>/dev/null || true
}
trap cleanup EXIT

require_tools() {
  local missing=()
  for t in ssh scp tar sha256sum mktemp; do
    command -v "${t}" >/dev/null 2>&1 || missing+=("${t}")
  done
  if (( ${#missing[@]} )); then
    err "missing required tools: ${missing[*]}"
    exit 1
  fi
}

# One SSH call that inventories + tarballs in a single remote shell. Stdout is
# the path to the remote tarball on success; stderr is human-readable progress.
#
# The heredoc is UNQUOTED so the local shell expands ${TRAEFIK_DIR} and
# ${TARGETS[*]} before piping to `bash -s` on the remote. Any $variable that
# should be evaluated remotely is escaped as \$.
inventory_and_tar_on_remote() {
  ssh "${SSH_OPTS[@]}" "${TRAEFIK_USER}@${TRAEFIK_HOST}" bash -s <<EOF
set -euo pipefail
cd ~/"${TRAEFIK_DIR}"

existing=()
for t in ${TARGETS[*]}; do
  if [ -e "\$t" ]; then
    existing+=("\$t")
    printf 'FOUND   %s\n' "\$t" >&2
  else
    printf 'MISSING %s\n' "\$t" >&2
  fi
done

if [ "\${#existing[@]}" -eq 0 ]; then
  printf 'ERROR: no target paths exist under ~/%s\n' "${TRAEFIK_DIR}" >&2
  exit 1
fi

tarball=\$(mktemp /tmp/traefik-backup-XXXXXX.tar.gz)
tar -czf "\${tarball}" "\${existing[@]}"
printf '%s\n' "\${tarball}"
EOF
}

main() {
  require_tools

  log "Opening SSH connection to ${TRAEFIK_USER}@${TRAEFIK_HOST} (passphrase prompt expected once)"
  # Prime the ControlMaster — first call prompts for passphrase, subsequent
  # ssh/scp invocations reuse the socket.
  if ! ssh "${SSH_OPTS[@]}" "${TRAEFIK_USER}@${TRAEFIK_HOST}" \
       "test -d ~/${TRAEFIK_DIR}"; then
    err "cannot reach ${TRAEFIK_USER}@${TRAEFIK_HOST} or ~/${TRAEFIK_DIR} does not exist"
    exit 1
  fi

  log "Inventorying target paths and creating tarball on remote"
  # Capture stdout (remote tarball path) while letting stderr (FOUND/MISSING
  # lines) flow to our stderr. Prefix remote messages so they're identifiable.
  local tarball_path
  tarball_path=$(inventory_and_tar_on_remote 2> >(sed 's/^/[traefik-backup:remote] /' >&2))

  if [[ -z "${tarball_path}" ]]; then
    err "remote tar produced no output — see warnings above"
    exit 1
  fi
  REMOTE_TARBALL="${tarball_path}"

  local hostname_short timestamp out_base
  hostname_short=$(ssh "${SSH_OPTS[@]}" "${TRAEFIK_USER}@${TRAEFIK_HOST}" hostname -s)
  timestamp=$(date -u +%Y%m%dT%H%M%SZ)
  out_base="traefik-backup-${hostname_short}-${timestamp}"

  mkdir -p "${OUT_DIR}"
  local local_tarball="${OUT_DIR}/${out_base}.tar.gz"
  local local_manifest="${OUT_DIR}/${out_base}.sha256"

  log "Downloading tarball to ${local_tarball}"
  scp "${SSH_OPTS[@]}" \
    "${TRAEFIK_USER}@${TRAEFIK_HOST}:${REMOTE_TARBALL}" \
    "${local_tarball}"

  log "Computing SHA256 manifest"
  ( cd "${OUT_DIR}" && sha256sum "${out_base}.tar.gz" > "${out_base}.sha256" )

  log "Verifying tarball integrity"
  ( cd "${OUT_DIR}" && sha256sum -c "${out_base}.sha256" >/dev/null )

  log ""
  log "=== Backup complete ==="
  log "Tarball:  ${local_tarball}"
  log "Manifest: ${local_manifest}"
  log "Size:     $(du -h "${local_tarball}" | awk '{print $1}')"
  log "Contents:"
  tar tzf "${local_tarball}" | sed 's/^/  /'
}

main "$@"
